# -*- coding: utf-8 -*-
"""fantasy statistics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UMsNmW4xO38ZlP8m6zRAGb60Z8KcqCk7
"""

from bs4 import BeautifulSoup
import pandas as pd
import requests
import matplotlib.pyplot as plt
opened_webpage = requests.get("https://www.fantasypros.com/nfl/stats/wr.php?scoring=PPR")
print ("Webpage opened successfully...")
print (opened_webpage.content)
bs = BeautifulSoup(opened_webpage.content, "html.parser")
print ("Webpage loaded and parsed successfully...")



# Find the table element with the data
table = bs.find('tbody')

# Initialize lists to store data
data_rows = []

# Extract data from each row in the table
for row in table.find_all('tr'):
    columns = row.find_all('td')
    data_row = [float(column.get_text(strip=True).replace(',', '')) if column.get_text(strip=True).replace(',', '').replace('.', '', 1).isdigit() else column.get_text(strip=True) for column in columns]
    data_rows.append(data_row)
labels = ["Rank", "Player", "REC", "TGT", "YDS", "Y/R", "LG", "20+", "TD", "ATT", "YDS", "TD", "FL", "G", "FPTS", "FPTS/G", "ROST"]

csv_file_path = 'fantasywrs.csv'


df = pd.DataFrame(data_rows, columns=labels)


df.to_csv(csv_file_path, index=False)





#from google.colab import files
#files.download(csv_file_path)

top10 = df.head(10)
top50 = df.head(50)
top100 = df.head(100)
top300 = df.head(300)

def vals(d) :
    avg = d["FPTS/G"].mean()
    med = d["FPTS/G"].median()
    stdv = d["FPTS/G"].std()
    print("mean","median","standard deviation")
    print(avg,med,stdv)
vals(top10)
vals(top50)
vals(top100)
vals(top300)



points10 = top10["FPTS/G"]
points50 = top50["FPTS/G"]
points100 = top100["FPTS/G"]
points300 = top300["FPTS/G"]
yds10 = top10["YDS"]
tgt10 = top10["TGT"]
def plot_bar_chart(df, x_column, y_column, title):
    df.plot(kind="bar", x=x_column, y=y_column, figsize=(10, 6), color='skyblue')
    plt.title(title)
    plt.xlabel(x_column)
    plt.ylabel(y_column)
    plt.show()

# Plot for Points (FPTS/G) for top 10
plot_bar_chart(top10, "Player", "FPTS/G", "Fantasy Points per Game for Top 10 Fantasy Wide Receivers")

# Plot for Yards (YDS) for top 10
plot_bar_chart(top10, "Player", "YDS", "Yards for Top 10 Fantasy Wide Receivers")

# Plot for Targets (TGT) for top 10
plot_bar_chart(top10, "Player", "TGT", "Targets for Top 10 Fantasy Wide Receivers")

# Plot for Receptions (REC) for top 10
plot_bar_chart(top10, "Player", "REC", "Receptions for Top 10 Fantasy Wide Receivers")



